description:
  "Make a feature request"
labels:
  - enhancement
name: "Feature Request"
body:
  - attributes:
      value: |
        Thank you for making a feature request for this project!
    type: markdown
  - attributes:
      label: "Preflight checklist"
      options:
        - label:
            "I could not find a solution in the existing issues, docs, nor
            discussions."
          required: true
        - label:
            "I agree to follow this project's Code of
            Conduct"
          required: true
    id: checklist
    type: checkboxes
  - attributes:
      description:
        "Is your feature request related to a problem? Please describe."
      label: "Describe your problem"
      placeholder:
        "A clear and concise description of what the problem is. Ex. I'm always
        frustrated when [...]"
    id: problem
    type: textarea
    validations:
      required: true
  - attributes:
      description: |
        Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
      label: "Describe your ideal solution"
    id: solution
    type: textarea
    validations:
      required: true
  - attributes:
      description: "Describe alternatives you've considered"
      label: "Workarounds or alternatives"
    id: alternatives
    type: textarea
    validations:
      required: true
  - attributes:
      description: "What version of our software are you running?"
      label: Version
    id: version
    type: input
    validations:
      required: true
  - attributes:
      description:
        "Add any other context or screenshots about the feature request here."
      label: Additional Context
    id: additional
    type: textarea
